### PR TITLE
Symfony 5 update because of TreeBuilder changes

### PR DESCRIPTION
**Pull request by ghost**
It seems as if the Lorem Ipsum bundle can't be used in Symfony 5 apps because `Symfony\Component\Config\Definition\Builder\TreeBuilder` was updated:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  ArgumentCountError {#3418
!!    #message: "Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /zebra/vendor/programarivm/lorem-ipsum-bundle/src/DependencyInjection/Configuration.php on line 12 and at least 1 expected"
!!    #code: 0
!!    #file: "./vendor/symfony/config/Definition/Builder/TreeBuilder.php"
!!    #line: 26
!!    trace: {
!!      ./vendor/symfony/config/Definition/Builder/TreeBuilder.php:26 { …}
!!      ./vendor/programarivm/lorem-ipsum-bundle/src/DependencyInjection/Configuration.php:12 { …}
!!      ./vendor/symfony/config/Definition/Processor.php:50 { …}
!!      ./vendor/symfony/dependency-injection/Extension/Extension.php:111 { …}
!!      ./vendor/programarivm/lorem-ipsum-bundle/src/DependencyInjection/KnpULoremIpsumExtension.php:20 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:734 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:545 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:126 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:169 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:75 { …}
!!      ./vendor/symfony/console/Application.php:141 { …}
!!      ./bin/console:42 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!        arguments: {
!!          $input: Symfony\Component\Console\Input\ArgvInput {#5 …}
!!        }
!!      }
!!    }
!!  }
!!  2020-02-16T09:06:05+00:00 [critical] Uncaught Error: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /zebra/vendor/programarivm/lorem-ipsum-bundle/src/DependencyInjection/Configuration.php on line 12 and at least 1 expected
!!  
Script @auto-scripts was called via post-update-cmd
```
By updating the `getConfigTreeBuilder()` method accordingly in `KnpU\LoremIpsumBundle\DependencyInjection\Configuration` now the bundle can be used in Symfony 5 apps as per this test: https://github.com/programarivm/zebra/commit/5345add7a245c57340c0f93038c9cae48b411d66

### CODE REVIEW

**Comment by programarivm** [comment]
Instead of merging this with `master`, possibly a good thing to do is to just create a new branch named `feature/symfony5-update`

**Comment by ghost** [comment]
Just closed this PR since I am not too clear it is backwards compatible with 3.4. Possibly a good thing to do would be to create a new branch for the bundle to support Symfony 5.

**Comment by bocharsky-bw** [comment]
Hey @programarivm 

Thank you for working on adding Symfony 5 support! We do want it working on Symfony 5, but it's too tight to video and code in our screencast https://symfonycasts.com/screencast/symfony-bundle . I'm going to discuss this with a team and probably I'll re-open this PR back.

Btw, does this bundle work for you on Symfony 5 _after_ the changes you've made here? Or do we need to do more changes here to get it working? Thanks!

**Comment by ghost** [comment]
Hi @bocharsky-bw 

Sorry for the delay in replying. My Symfony 5 host application throws the following error when running the `lorem-ipsum-bundle` tests if using `symfony/framework-bundle` version 5.0:

```
docker exec -it zebra_php_fpm php bin/phpunit vendor/programarivm/lorem-ipsum-bundle
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing vendor/programarivm/lorem-ipsum-bundle
E....                                                               5 / 5 (100%)

Time: 151 ms, Memory: 8.00 MB

There was 1 error:

1) KnpU\LoremIpsumBundle\Tests\Controller\IpsumApiControllerTest::testIndex
Error: Class 'Symfony\Bundle\FrameworkBundle\Client' not found

/zebra/vendor/programarivm/lorem-ipsum-bundle/tests/Controller/IpsumApiControllerTest.php:20

ERRORS!
Tests: 5, Assertions: 660, Errors: 1.
```
`Symfony\Bundle\FrameworkBundle\Client` is missing in `symfony/framework-bundle`.

On a different side note I was able to successfully set up [`programarivm/easy-acl-bundle`](https://github.com/programarivm/easy-acl-bundle) which is a Symfony 5 bundle without any functional tests for the time being:

```
docker exec -it zebra_php_fpm php bin/phpunit vendor/programarivm/easy-acl-bundle
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing vendor/programarivm/easy-acl-bundle
...                                                                 3 / 3 (100%)

Time: 85 ms, Memory: 6.00 MB

OK (3 tests, 658 assertions)
```
Also I thought that I'd possibly remove the `require-dev` packages in [`easy-acl-bundle/composer.json`](https://github.com/programarivm/easy-acl-bundle/blob/master/composer.json) provided that those are intended to be installed in the testing host application:

- [Composer won't install “require-dev” packages](https://stackoverflow.com/questions/21154216/composer-wont-install-require-dev-packages)

**Comment by weaverryan** [comment]
Hi @programarivm!

> Symfony\Bundle\FrameworkBundle\Client is missing in symfony/framework-bundle.

Indeed! It was deprecated and removed in Symfony 5.0. Try this class instead: https://github.com/symfony/symfony/blob/5.0/src/Symfony/Bundle/FrameworkBundle/KernelBrowser.php

> Also I thought that I'd possibly remove the require-dev packages in easy-acl-bundle/composer.json provided that those are intended to be installed in the testing host application

It looks like you already did this :) https://github.com/programarivm/easy-acl-bundle/commit/7df6dc5d29fce4b98499657e7a36a2d0cf48a355 - you were correct to do that.

Cheers!

**Comment by ghost** [comment]
Hello @weaverryan 

Thanks for the feedback, it is very much appreciated! I guess I'll look at the functional tests at some point when dealing with routes.

**Comment by programarivm** [comment]
Thanks for your help again.

Finally, today I was able to also set up [`programarivm/doctrine-behavior-bundle`](https://github.com/programarivm/doctrine-behavior-bundle) which might be the simplest bundle ever, given the fact it uses PHP Traits only.

**Pull request closed without merging**
